### ISSUE TITLE
Don't fail if apt-get update fails

### ISSUE THREAD

**Issue by vkurup** [caktus/fabulaws#40]
When running `fab create_environment`, one or more of the servers failed completely when apt-get update failed:

```
[ec2-54-204-126-125.compute-1.amazonaws.com] sudo: apt-get -qq update
[ec2-54-204-126-125.compute-1.amazonaws.com] out: W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/universe/i18n/Translation-en  Hash Sum mismatch
[ec2-54-204-126-125.compute-1.amazonaws.com] out: 
[ec2-54-204-126-125.compute-1.amazonaws.com] out: E: Some index files failed to download. They have been ignored, or old ones used instead.
[ec2-54-204-126-125.compute-1.amazonaws.com] out: 


Fatal error: sudo() received nonzero return code 100 while executing!

Requested: apt-get -qq update
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "apt-get -qq update"

Aborting.

Fatal error: One or more hosts failed while executing task 'install_newrelic_sysmon'

Aborting.
Left volume "vol-22b369fc" in state "in-use"
Left instance "i-d170fb52" running at ec2-54-204-126-125.compute-1.amazonaws.com
```

This usually left the entire environment in a bad state, so, without knowing a better option, I either recreated the single server, or recreated the whole environment again.

I changed the apt-get update commands to run inside a 'warn_only' context manager, and this allowed the commands to succeed, without causing the entire server creation to fail. This also still showed me the warnings in the logs, so I could redo an apt-get update, if I felt it necessary after server creation.

**Comment by dpoirier** [comment]
Amazon's mirrors of ubuntu package repos might be more reliable from inside AWS.

We could also just change `apt-get xxxx` to `apt-get xxx || apt-get xxx` in hopes that it'll work on the retry.

**Comment by vkurup** [comment]
FWIW, I was using amazon's mirror.

**Comment by dpoirier** [comment]
The example error given in an earlier comment was failing on "http://security.ubuntu.com".

**Comment by vkurup** [comment]
Yeah, I just noticed that. I'm not sure if all 'security' links go to security.ubuntu.com, or if this particular error was from before I removed the `ubuntu_mirror` value, but I definitely tried changing this to use the AWS repos and still had the same issues.
